### ISSUE TITLE
NPE when user not registered on site uses !log command

### ISSUE THREAD

**Issue by evansloan** [evansloan/collection-log#37]
```
2023-05-27 23:04:10 EDT [OkHttp Dispatcher] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.NullPointerException: null
	at com.evansloan.collectionlog.CollectionLogPlugin$1.onResponse(CollectionLogPlugin.java:943)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Does not impact functionality of the plugin, but should be cleaned up anyway

**Comment by evansloan** [comment]
Fixed in 3aba5600c6cfe96127fb84554f825b052ef8f384
