### ISSUE TITLE
Collection log widget crash 

### ISSUE THREAD

**Issue by peanubnutter** [evansloan/collection-log#48]
None of the normal collection log functionality is working on opening the collection log because exceptions are being thrown, which I think may be caused by the change to getCollectionLogTitle():

2024-02-04 00:55:12 PST [Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
at com.evansloan.collectionlog.CollectionLogPlugin.getCollectionLogTitle(CollectionLogPlugin.java:1116)
at com.evansloan.collectionlog.CollectionLogPlugin.setCollectionLogTitle(CollectionLogPlugin.java:879)
at com.evansloan.collectionlog.CollectionLogPlugin.setCollectionLogTitle(CollectionLogPlugin.java:869)
at com.evansloan.collectionlog.CollectionLogPlugin.update(CollectionLogPlugin.java:861)
at com.evansloan.collectionlog.CollectionLogPlugin.getPage(CollectionLogPlugin.java:691)
at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:80)
at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
at net.runelite.client.callback.Hooks.tick(Hooks.java:218)
at client.uz(client.java:2380)
at client.bc(client.java)
at by.za(by.java:403)
at by.io(by.java)
at by.run(by.java:7195)
at java.base/java.lang.Thread.run(Thread.java:829)

Looks like the plugin crashes and doesn't display collection log widget text properly.

**Comment by peanubnutter** [comment]
Caused by https://github.com/evansloan/collection-log/commit/93d8e56d73f6e51f5fbbbcc3cf113a295517adc2
